name: Bump version
on:
  workflow_dispatch:
    inputs:
      type:
        description: "Version bump"
        type: choice
        options:
          - patch
          - minor
          - major
        default: patch
jobs:
  bump:
    uses: Appegy/upm-ci/.github/workflows/bump-version.yml@v1
    with:
      type: ${{ inputs.type }}
    secrets: inherit
